👷 Run Continuous Integration via `actions-rs/cargo`
Use https://github.com/actions-rs/cargo instead of
https://github.com/icepuma/rust-action (which seems
stuck with Rust 1.68) so that Rust 1.69 can be used
during CI.

Use 'ubuntu-20.04' because CI failed with 'ubuntu-latest' (i.e. 'ubuntu-22.04', cf. https://github.com/actions/runner-images) 🤷‍♂️:

	Error: failed to run custom build command for `openssl-sys v0.9.58`
	Caused by:
	  process didn't exit successfully: `/home/runner/work/pullpito/pullpito/target/debug/build/openssl-sys-86ddd9c2fa3d5d68/build-script-main` (exit status: 101)
	  --- stdout
	  cargo:rustc-cfg=const_fn
	  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
	  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
	  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
	  OPENSSL_LIB_DIR unset
	  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
	  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
	  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
	  OPENSSL_INCLUDE_DIR unset
	  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
	  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
	  cargo:rerun-if-env-changed=OPENSSL_DIR
	  OPENSSL_DIR unset
	  cargo:rustc-link-lib=ssl
	  cargo:rustc-link-lib=crypto
	  OPT_LEVEL = Some("0")
	  TARGET = Some("x86_64-unknown-linux-gnu")
	  HOST = Some("x86_64-unknown-linux-gnu")
	  CC_x86_64-unknown-linux-gnu = None
	  CC_x86_64_unknown_linux_gnu = None
	  HOST_CC = None
	  CC = None
	  CFLAGS_x86_64-unknown-linux-gnu = None
	  CFLAGS_x86_64_unknown_linux_gnu = None
	  HOST_CFLAGS = None
	  CFLAGS = None
	  CRATE_CC_NO_DEFAULTS = None
	  DEBUG = Some("true")
	  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
	  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/usr/include" "-Wall" "-Wextra" "-E" "build/expando.c"
	  cargo:warning=build/expando.c:4:24: error: pasting "RUST_VERSION_OPENSSL_" and "(" does not give a valid preprocessing token
	  cargo:warning=    4 | #define VERSION2(n, v) RUST_VERSION_##n##_##v
	  cargo:warning=      |                        ^~~~~~~~~~~~~
	  cargo:warning=build/expando.c:5:23: note: in expansion of macro ‘VERSION2’
	  cargo:warning=    5 | #define VERSION(n, v) VERSION2(n, v)
	  cargo:warning=      |                       ^~~~~~~~
	  cargo:warning=build/expando.c:10:1: note: in expansion of macro ‘VERSION’
	  cargo:warning=   10 | VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
	  cargo:warning=      | ^~~~~~~
	  exit status: 1

	  --- stderr
	  thread 'main' panicked at '
	  Header expansion error:
	  Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-g\" \"-fno-omit-frame-pointer\" \"-m64\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

	  Failed to find OpenSSL development headers.