🔒 Fix vulnerability RUSTSEC-2019-0011
Upgraded libraries to latest in order to fix RUSTSEC-2019-0011
seen via `cargo audit`.

Before:

	$ cargo audit

	error: Vulnerable crates found!

	ID:       RUSTSEC-2019-0011
	Crate:    memoffset
	Version:  0.2.1
	Date:     2019-07-16
	URL:      https://rustsec.org/advisories/RUSTSEC-2019-0011
	Title:    Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
	Solution:  upgrade to >= 0.5.0
	Dependency tree:
	memoffset 0.2.1
	└── crossbeam-epoch 0.7.1
	    └── crossbeam-deque 0.7.1
	        └── tokio-threadpool 0.1.14
	            ├── tokio 0.1.21
	            │   ├── reqwest 0.9.22
	            │   │   └── pullpito 0.1.0
	            │   └── hyper 0.12.35
	            │       ├── reqwest 0.9.22
	            │       └── hyper-tls 0.3.2
	            │           └── reqwest 0.9.22
	            ├── reqwest 0.9.22
	            └── hyper 0.12.35

	warning: 2 warnings found

	Crate:  net2
	Title:  `net2` crate has been deprecated; use `socket2` instead
	Date:   2020-05-01
	URL:    https://rustsec.org/advisories/RUSTSEC-2020-0016
	Dependency tree:
	net2 0.2.33
	├── miow 0.2.1
	│   └── mio 0.6.19
	│       ├── tokio-tcp 0.1.3
	│       │   ├── tokio 0.1.21
	│       │   │   ├── reqwest 0.9.22
	│       │   │   │   └── pullpito 0.1.0
	│       │   │   └── hyper 0.12.35
	│       │   │       ├── reqwest 0.9.22
	│       │   │       └── hyper-tls 0.3.2
	│       │   │           └── reqwest 0.9.22
	│       │   └── hyper 0.12.35
	│       ├── tokio-reactor 0.1.9
	│       │   ├── tokio-tcp 0.1.3
	│       │   ├── tokio 0.1.21
	│       │   └── hyper 0.12.35
	│       └── tokio 0.1.21
	├── mio 0.6.19
	└── hyper 0.12.35

	Crate:    quote
	Version:  1.0.2
	Warning:  package has been yanked!
	Dependency tree:
	quote 1.0.2
	├── synstructure 0.12.1
	│   └── failure_derive 0.1.6
	│       └── failure 0.1.6
	│           └── cookie_store 0.7.0
	│               └── reqwest 0.9.22
	│                   └── pullpito 0.1.0
	├── syn 1.0.7
	│   ├── synstructure 0.12.1
	│   ├── structopt-derive 0.3.5
	│   │   └── structopt 0.3.5
	│   │       └── pullpito 0.1.0
	│   ├── serde_derive 1.0.104
	│   │   ├── serde 1.0.104
	│   │   │   ├── serde_urlencoded 0.5.5
	│   │   │   │   └── reqwest 0.9.22
	│   │   │   ├── serde_json 1.0.45
	│   │   │   │   ├── reqwest 0.9.22
	│   │   │   │   ├── pullpito 0.1.0
	│   │   │   │   └── cookie_store 0.7.0
	│   │   │   ├── reqwest 0.9.22
	│   │   │   ├── pullpito 0.1.0
	│   │   │   ├── cookie_store 0.7.0
	│   │   │   └── chrono 0.4.10
	│   │   │       └── pullpito 0.1.0
	│   │   └── pullpito 0.1.0
	│   ├── proc-macro-hack 0.5.11
	│   │   ├── futures-util 0.3.1
	│   │   │   ├── futures-executor 0.3.1
	│   │   │   │   └── futures 0.3.1
	│   │   │   │       └── pullpito 0.1.0
	│   │   │   └── futures 0.3.1
	│   │   └── futures-macro 0.3.1
	│   │       └── futures-util 0.3.1
	│   ├── proc-macro-error 0.2.6
	│   │   └── structopt-derive 0.3.5
	│   ├── futures-macro 0.3.1
	│   └── failure_derive 0.1.6
	├── structopt-derive 0.3.5
	├── serde_derive 1.0.104
	├── proc-macro-hack 0.5.11
	├── proc-macro-error 0.2.6
	├── futures-macro 0.3.1
	└── failure_derive 0.1.6

	error: 1 vulnerability found!
	warning: 2 warnings found!

Now:

	$ cargo audit

	warning: 1 warning found

	Crate:  net2
	Title:  `net2` crate has been deprecated; use `socket2` instead
	Date:   2020-05-01
	URL:    https://rustsec.org/advisories/RUSTSEC-2020-0016
	Dependency tree:
	net2 0.2.34
	├── miow 0.2.1
	│   └── mio 0.6.22
	│       ├── tokio-tcp 0.1.4
	│       │   ├── tokio 0.1.22
	│       │   │   ├── reqwest 0.9.24
	│       │   │   │   └── pullpito 0.1.0
	│       │   │   └── hyper 0.12.35
	│       │   │       ├── reqwest 0.9.24
	│       │   │       └── hyper-tls 0.3.2
	│       │   │           └── reqwest 0.9.24
	│       │   └── hyper 0.12.35
	│       ├── tokio-reactor 0.1.12
	│       │   ├── tokio-tcp 0.1.4
	│       │   ├── tokio 0.1.22
	│       │   └── hyper 0.12.35
	│       └── tokio 0.1.22
	├── mio 0.6.22
	└── hyper 0.12.35

	warning: 1 warning found!